/**:
  ros__parameters:
    common:
      # lid_topic: "/ouster/points"
      lid_topic: "/os_cloud_node/points"
      # imu_topic: "/imu/data_raw"
      imu_topic: "/xsens_imu_data"
      time_sync_en: false
      time_offset_lidar_to_imu: 0.0

    preprocess:
      lidar_type: 3
      scan_line: 128
      scan_rate: 10
      timestamp_unit: 3
      blind: 1.0

    mapping:
      acc_cov: 0.0111974126
      gyr_cov: 0.0102709048
      b_acc_cov: 0.0001175176
      b_gyr_cov: 0.0000913553
      fov_degree: 180.0
      det_range: 100.0
      extrinsic_est_en: true
      extrinsic_T: [0.215, 0.0, 0.018]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      # extrinsic_T: [-1.2574, 0.413, 0.0324]
      # extrinsic_R: [0.0, -1.0, 0.0,
      #               1.0,  0.0, 0.0,
      #               0.0,  0.0, 1.0]

    publish:
      path_en: true
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: true

    pcd_save:
      pcd_save_en: false
      interval: -1

    feature_extract_enable: false
    point_filter_num: 1
    filter_size_surf: 0.2
    filter_size_map: 0.2
    filter_size_corner: 0.2
    cube_side_length: 1000.0
    max_iteration: 3
    runtime_pos_log_enable: false
# /**:
#   ros__parameters:
#     common:
#       lid_topic:  "/ouster/points"
#       imu_topic:  "/imu/data_raw"
#       time_sync_en: false
#       time_offset_lidar_to_imu: 0.0

#     preprocess:
#       lidar_type: 3                # 3 tương ứng với cảm biến Ouster
#       scan_line: 128               # Số tia của Ouster trong dataset này
#       timestamp_unit: 3            # 0 = Giây (seconds), 3 = nanoseconds
#       # blind: 0.0
#       blink: 1.0

#     mapping:
#       acc_cov: 0.0111974126
#       gyr_cov: 0.0102709048
#       b_acc_cov: 0.0001175176
#       b_gyr_cov: 0.0000913553
#       fov_degree: 180.0
#       det_range: 100.0
#       extrinsic_est_en: true
      
#       # Tọa độ tịnh tiến của Ouster (từ mảng T gốc)
#       extrinsic_T: [ 0.215, 0.0, 0.018 ]
      
#       # Quaternion [1, 0, 0, 0] của Ouster quy đổi ra Ma trận xoay 3x3 (Identity Matrix)
#       extrinsic_R: [ 1.0, 0.0, 0.0,
#                      0.0, 1.0, 0.0,
#                      0.0, 0.0, 1.0 ]

#     publish:
#       path_en: true
#       scan_publish_en: true
#       dense_publish_en: true
#       scan_bodyframe_pub_en: true

#     pcd_save:
#       pcd_save_en: true
#       interval: -1

#     uncertainty:
#       point_cov_max: 0.00125
#       point_cov_min: 0.00075
#       plane_cov_max: 1.0
#       plane_cov_min: 0.8
#       localize_cov_max: 2.0
#       localize_cov_min: 0.3
#       localize_thresh_max: 0.7
#       localize_thresh_min: 0.2
#       cov_threshold: 0.5